# Generated by Django 6.0.3 on 2026-04-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('prescription', models.TextField()),
                ('patient_img', models.URLField(null=True)),
            ],
        ),
    ]
