# Generated by Django 6.0.3 on 2026-05-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='patient_img',
        ),
    ]
